// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wujiahao/Desktop/sma/Demo/MagicPlayer/node_modules/dumi/theme-default/slots/SocialIcon/index.js';
